//go:build !uint256

// Code generated by go-abi. DO NOT EDIT.

package tests

import (
	"io"
	"math/big"

	"github.com/ethereum/go-ethereum/common"
	"github.com/yihuang/go-abi"
)

// Function selectors
var (
	// packedBool(bool,bool)
	PackedBoolSelector = [4]byte{0x7c, 0x64, 0x32, 0x8c}
	// packedBytes(bytes32,bytes4)
	PackedBytesSelector = [4]byte{0xfb, 0x04, 0x69, 0xe0}
	// packedIntermediate(uint24,uint40,int24,int40)
	PackedIntermediateSelector = [4]byte{0x11, 0xfe, 0xe1, 0x68}
	// packedSmallInts(uint8,uint16,uint32,uint64,int8,int16,int32,int64)
	PackedSmallIntsSelector = [4]byte{0xe3, 0xfb, 0x85, 0xd2}
	// packedStruct((address,uint256,bytes32))
	PackedStructSelector = [4]byte{0x95, 0xeb, 0x92, 0x1c}
	// packedTransfer(address,uint256)
	PackedTransferSelector = [4]byte{0x59, 0x74, 0xfe, 0x12}
)

// Big endian integer versions of function selectors
const (
	PackedBoolID         = 2086941324
	PackedBytesID        = 4211370464
	PackedIntermediateID = 301916520
	PackedSmallIntsID    = 3824911826
	PackedStructID       = 2515243548
	PackedTransferID     = 1500839442
)

const PackedStructStaticSize = 96

var _ abi.Tuple = (*PackedStruct)(nil)
var _ abi.PackedTuple = (*PackedStruct)(nil)

// PackedStruct represents an ABI tuple
type PackedStruct struct {
	Addr  common.Address
	Value *big.Int
	Data  [32]byte
}

// EncodedSize returns the total encoded size of PackedStruct
func (t PackedStruct) EncodedSize() int {
	dynamicSize := 0

	return PackedStructStaticSize + dynamicSize
}

// EncodeTo encodes PackedStruct to ABI bytes in the provided buffer
func (value PackedStruct) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := PackedStructStaticSize // Start dynamic data after static section
	// Field Addr: address
	if _, err := abi.EncodeAddress(value.Addr, buf[0:]); err != nil {
		return 0, err
	}

	// Field Value: uint256
	if _, err := abi.EncodeUint256(value.Value, buf[32:]); err != nil {
		return 0, err
	}

	// Field Data: bytes32
	if _, err := abi.EncodeBytes32(value.Data, buf[64:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes PackedStruct to ABI bytes
func (value PackedStruct) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes PackedStruct from ABI bytes in the provided buffer
func (t *PackedStruct) Decode(data []byte) (int, error) {
	if len(data) < 96 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 96
	// Decode static field Addr: address
	t.Addr, _, err = abi.DecodeAddress(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode static field Value: uint256
	t.Value, _, err = abi.DecodeUint256(data[32:])
	if err != nil {
		return 0, err
	}
	// Decode static field Data: bytes32
	t.Data, _, err = abi.DecodeBytes32(data[64:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

// PackedEncodedSize returns the packed encoded size of PackedStruct
func (t PackedStruct) PackedEncodedSize() int {
	return 84
}

// PackedEncodeTo encodes PackedStruct to packed ABI bytes in the provided buffer
func (value PackedStruct) PackedEncodeTo(buf []byte) (int, error) {
	// Encode tuple fields sequentially (packed, no dynamic section)
	var (
		offset int
		n      int
		err    error
	)
	// Field Addr: address
	n, err = abi.PackedEncodeAddress(value.Addr, buf[offset:])
	if err != nil {
		return 0, err
	}
	offset += n

	// Field Value: uint256
	n, err = abi.PackedEncodeUint256(value.Value, buf[offset:])
	if err != nil {
		return 0, err
	}
	offset += n

	// Field Data: bytes32
	n, err = abi.PackedEncodeBytes32(value.Data, buf[offset:])
	if err != nil {
		return 0, err
	}
	offset += n

	return offset, nil
}

// PackedEncode encodes PackedStruct to packed ABI bytes
func (value PackedStruct) PackedEncode() ([]byte, error) {
	buf := make([]byte, value.PackedEncodedSize())
	if _, err := value.PackedEncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// PackedDecode decodes PackedStruct from packed ABI bytes
func (t *PackedStruct) PackedDecode(data []byte) (int, error) {
	if len(data) < 84 {
		return 0, io.ErrUnexpectedEOF
	}
	var err error
	// Decode field Addr: address
	t.Addr, _, err = abi.PackedDecodeAddress(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode field Value: uint256
	t.Value, _, err = abi.PackedDecodeUint256(data[20:])
	if err != nil {
		return 0, err
	}
	// Decode field Data: bytes32
	t.Data, _, err = abi.PackedDecodeBytes32(data[52:])
	if err != nil {
		return 0, err
	}
	return 84, nil
}

var _ abi.Method = (*PackedBoolCall)(nil)

const PackedBoolCallStaticSize = 64

var _ abi.Tuple = (*PackedBoolCall)(nil)
var _ abi.PackedTuple = (*PackedBoolCall)(nil)

// PackedBoolCall represents an ABI tuple
type PackedBoolCall struct {
	A bool
	B bool
}

// EncodedSize returns the total encoded size of PackedBoolCall
func (t PackedBoolCall) EncodedSize() int {
	dynamicSize := 0

	return PackedBoolCallStaticSize + dynamicSize
}

// EncodeTo encodes PackedBoolCall to ABI bytes in the provided buffer
func (value PackedBoolCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := PackedBoolCallStaticSize // Start dynamic data after static section
	// Field A: bool
	if _, err := abi.EncodeBool(value.A, buf[0:]); err != nil {
		return 0, err
	}

	// Field B: bool
	if _, err := abi.EncodeBool(value.B, buf[32:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes PackedBoolCall to ABI bytes
func (value PackedBoolCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes PackedBoolCall from ABI bytes in the provided buffer
func (t *PackedBoolCall) Decode(data []byte) (int, error) {
	if len(data) < 64 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 64
	// Decode static field A: bool
	t.A, _, err = abi.DecodeBool(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode static field B: bool
	t.B, _, err = abi.DecodeBool(data[32:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

// PackedEncodedSize returns the packed encoded size of PackedBoolCall
func (t PackedBoolCall) PackedEncodedSize() int {
	return 2
}

// PackedEncodeTo encodes PackedBoolCall to packed ABI bytes in the provided buffer
func (value PackedBoolCall) PackedEncodeTo(buf []byte) (int, error) {
	// Encode tuple fields sequentially (packed, no dynamic section)
	var (
		offset int
		n      int
		err    error
	)
	// Field A: bool
	n, err = abi.PackedEncodeBool(value.A, buf[offset:])
	if err != nil {
		return 0, err
	}
	offset += n

	// Field B: bool
	n, err = abi.PackedEncodeBool(value.B, buf[offset:])
	if err != nil {
		return 0, err
	}
	offset += n

	return offset, nil
}

// PackedEncode encodes PackedBoolCall to packed ABI bytes
func (value PackedBoolCall) PackedEncode() ([]byte, error) {
	buf := make([]byte, value.PackedEncodedSize())
	if _, err := value.PackedEncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// PackedDecode decodes PackedBoolCall from packed ABI bytes
func (t *PackedBoolCall) PackedDecode(data []byte) (int, error) {
	if len(data) < 2 {
		return 0, io.ErrUnexpectedEOF
	}
	var err error
	// Decode field A: bool
	t.A, _, err = abi.PackedDecodeBool(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode field B: bool
	t.B, _, err = abi.PackedDecodeBool(data[1:])
	if err != nil {
		return 0, err
	}
	return 2, nil
}

// GetMethodName returns the function name
func (t PackedBoolCall) GetMethodName() string {
	return "packedBool"
}

// GetMethodID returns the function id
func (t PackedBoolCall) GetMethodID() uint32 {
	return PackedBoolID
}

// GetMethodSelector returns the function selector
func (t PackedBoolCall) GetMethodSelector() [4]byte {
	return PackedBoolSelector
}

// EncodeWithSelector encodes packedBool arguments to ABI bytes including function selector
func (t PackedBoolCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], PackedBoolSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewPackedBoolCall constructs a new PackedBoolCall
func NewPackedBoolCall(
	a bool,
	b bool,
) *PackedBoolCall {
	return &PackedBoolCall{
		A: a,
		B: b,
	}
}

const PackedBoolReturnStaticSize = 32

var _ abi.Tuple = (*PackedBoolReturn)(nil)
var _ abi.PackedTuple = (*PackedBoolReturn)(nil)

// PackedBoolReturn represents an ABI tuple
type PackedBoolReturn struct {
	Field1 bool
}

// EncodedSize returns the total encoded size of PackedBoolReturn
func (t PackedBoolReturn) EncodedSize() int {
	dynamicSize := 0

	return PackedBoolReturnStaticSize + dynamicSize
}

// EncodeTo encodes PackedBoolReturn to ABI bytes in the provided buffer
func (value PackedBoolReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := PackedBoolReturnStaticSize // Start dynamic data after static section
	// Field Field1: bool
	if _, err := abi.EncodeBool(value.Field1, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes PackedBoolReturn to ABI bytes
func (value PackedBoolReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes PackedBoolReturn from ABI bytes in the provided buffer
func (t *PackedBoolReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field Field1: bool
	t.Field1, _, err = abi.DecodeBool(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

// PackedEncodedSize returns the packed encoded size of PackedBoolReturn
func (t PackedBoolReturn) PackedEncodedSize() int {
	return 1
}

// PackedEncodeTo encodes PackedBoolReturn to packed ABI bytes in the provided buffer
func (value PackedBoolReturn) PackedEncodeTo(buf []byte) (int, error) {
	// Encode tuple fields sequentially (packed, no dynamic section)
	var (
		offset int
		n      int
		err    error
	)
	// Field Field1: bool
	n, err = abi.PackedEncodeBool(value.Field1, buf[offset:])
	if err != nil {
		return 0, err
	}
	offset += n

	return offset, nil
}

// PackedEncode encodes PackedBoolReturn to packed ABI bytes
func (value PackedBoolReturn) PackedEncode() ([]byte, error) {
	buf := make([]byte, value.PackedEncodedSize())
	if _, err := value.PackedEncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// PackedDecode decodes PackedBoolReturn from packed ABI bytes
func (t *PackedBoolReturn) PackedDecode(data []byte) (int, error) {
	if len(data) < 1 {
		return 0, io.ErrUnexpectedEOF
	}
	var err error
	// Decode field Field1: bool
	t.Field1, _, err = abi.PackedDecodeBool(data[0:])
	if err != nil {
		return 0, err
	}
	return 1, nil
}

var _ abi.Method = (*PackedBytesCall)(nil)

const PackedBytesCallStaticSize = 64

var _ abi.Tuple = (*PackedBytesCall)(nil)
var _ abi.PackedTuple = (*PackedBytesCall)(nil)

// PackedBytesCall represents an ABI tuple
type PackedBytesCall struct {
	B32 [32]byte
	B4  [4]byte
}

// EncodedSize returns the total encoded size of PackedBytesCall
func (t PackedBytesCall) EncodedSize() int {
	dynamicSize := 0

	return PackedBytesCallStaticSize + dynamicSize
}

// EncodeTo encodes PackedBytesCall to ABI bytes in the provided buffer
func (value PackedBytesCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := PackedBytesCallStaticSize // Start dynamic data after static section
	// Field B32: bytes32
	if _, err := abi.EncodeBytes32(value.B32, buf[0:]); err != nil {
		return 0, err
	}

	// Field B4: bytes4
	if _, err := abi.EncodeBytes4(value.B4, buf[32:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes PackedBytesCall to ABI bytes
func (value PackedBytesCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes PackedBytesCall from ABI bytes in the provided buffer
func (t *PackedBytesCall) Decode(data []byte) (int, error) {
	if len(data) < 64 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 64
	// Decode static field B32: bytes32
	t.B32, _, err = abi.DecodeBytes32(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode static field B4: bytes4
	t.B4, _, err = abi.DecodeBytes4(data[32:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

// PackedEncodedSize returns the packed encoded size of PackedBytesCall
func (t PackedBytesCall) PackedEncodedSize() int {
	return 36
}

// PackedEncodeTo encodes PackedBytesCall to packed ABI bytes in the provided buffer
func (value PackedBytesCall) PackedEncodeTo(buf []byte) (int, error) {
	// Encode tuple fields sequentially (packed, no dynamic section)
	var (
		offset int
		n      int
		err    error
	)
	// Field B32: bytes32
	n, err = abi.PackedEncodeBytes32(value.B32, buf[offset:])
	if err != nil {
		return 0, err
	}
	offset += n

	// Field B4: bytes4
	n, err = abi.PackedEncodeBytes4(value.B4, buf[offset:])
	if err != nil {
		return 0, err
	}
	offset += n

	return offset, nil
}

// PackedEncode encodes PackedBytesCall to packed ABI bytes
func (value PackedBytesCall) PackedEncode() ([]byte, error) {
	buf := make([]byte, value.PackedEncodedSize())
	if _, err := value.PackedEncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// PackedDecode decodes PackedBytesCall from packed ABI bytes
func (t *PackedBytesCall) PackedDecode(data []byte) (int, error) {
	if len(data) < 36 {
		return 0, io.ErrUnexpectedEOF
	}
	var err error
	// Decode field B32: bytes32
	t.B32, _, err = abi.PackedDecodeBytes32(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode field B4: bytes4
	t.B4, _, err = abi.PackedDecodeBytes4(data[32:])
	if err != nil {
		return 0, err
	}
	return 36, nil
}

// GetMethodName returns the function name
func (t PackedBytesCall) GetMethodName() string {
	return "packedBytes"
}

// GetMethodID returns the function id
func (t PackedBytesCall) GetMethodID() uint32 {
	return PackedBytesID
}

// GetMethodSelector returns the function selector
func (t PackedBytesCall) GetMethodSelector() [4]byte {
	return PackedBytesSelector
}

// EncodeWithSelector encodes packedBytes arguments to ABI bytes including function selector
func (t PackedBytesCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], PackedBytesSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewPackedBytesCall constructs a new PackedBytesCall
func NewPackedBytesCall(
	b32 [32]byte,
	b4 [4]byte,
) *PackedBytesCall {
	return &PackedBytesCall{
		B32: b32,
		B4:  b4,
	}
}

const PackedBytesReturnStaticSize = 32

var _ abi.Tuple = (*PackedBytesReturn)(nil)
var _ abi.PackedTuple = (*PackedBytesReturn)(nil)

// PackedBytesReturn represents an ABI tuple
type PackedBytesReturn struct {
	Field1 bool
}

// EncodedSize returns the total encoded size of PackedBytesReturn
func (t PackedBytesReturn) EncodedSize() int {
	dynamicSize := 0

	return PackedBytesReturnStaticSize + dynamicSize
}

// EncodeTo encodes PackedBytesReturn to ABI bytes in the provided buffer
func (value PackedBytesReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := PackedBytesReturnStaticSize // Start dynamic data after static section
	// Field Field1: bool
	if _, err := abi.EncodeBool(value.Field1, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes PackedBytesReturn to ABI bytes
func (value PackedBytesReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes PackedBytesReturn from ABI bytes in the provided buffer
func (t *PackedBytesReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field Field1: bool
	t.Field1, _, err = abi.DecodeBool(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

// PackedEncodedSize returns the packed encoded size of PackedBytesReturn
func (t PackedBytesReturn) PackedEncodedSize() int {
	return 1
}

// PackedEncodeTo encodes PackedBytesReturn to packed ABI bytes in the provided buffer
func (value PackedBytesReturn) PackedEncodeTo(buf []byte) (int, error) {
	// Encode tuple fields sequentially (packed, no dynamic section)
	var (
		offset int
		n      int
		err    error
	)
	// Field Field1: bool
	n, err = abi.PackedEncodeBool(value.Field1, buf[offset:])
	if err != nil {
		return 0, err
	}
	offset += n

	return offset, nil
}

// PackedEncode encodes PackedBytesReturn to packed ABI bytes
func (value PackedBytesReturn) PackedEncode() ([]byte, error) {
	buf := make([]byte, value.PackedEncodedSize())
	if _, err := value.PackedEncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// PackedDecode decodes PackedBytesReturn from packed ABI bytes
func (t *PackedBytesReturn) PackedDecode(data []byte) (int, error) {
	if len(data) < 1 {
		return 0, io.ErrUnexpectedEOF
	}
	var err error
	// Decode field Field1: bool
	t.Field1, _, err = abi.PackedDecodeBool(data[0:])
	if err != nil {
		return 0, err
	}
	return 1, nil
}

var _ abi.Method = (*PackedIntermediateCall)(nil)

const PackedIntermediateCallStaticSize = 128

var _ abi.Tuple = (*PackedIntermediateCall)(nil)
var _ abi.PackedTuple = (*PackedIntermediateCall)(nil)

// PackedIntermediateCall represents an ABI tuple
type PackedIntermediateCall struct {
	U24 uint32
	U40 uint64
	I24 int32
	I40 int64
}

// EncodedSize returns the total encoded size of PackedIntermediateCall
func (t PackedIntermediateCall) EncodedSize() int {
	dynamicSize := 0

	return PackedIntermediateCallStaticSize + dynamicSize
}

// EncodeTo encodes PackedIntermediateCall to ABI bytes in the provided buffer
func (value PackedIntermediateCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := PackedIntermediateCallStaticSize // Start dynamic data after static section
	// Field U24: uint24
	if _, err := abi.EncodeUint24(value.U24, buf[0:]); err != nil {
		return 0, err
	}

	// Field U40: uint40
	if _, err := abi.EncodeUint40(value.U40, buf[32:]); err != nil {
		return 0, err
	}

	// Field I24: int24
	if _, err := abi.EncodeInt24(value.I24, buf[64:]); err != nil {
		return 0, err
	}

	// Field I40: int40
	if _, err := abi.EncodeInt40(value.I40, buf[96:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes PackedIntermediateCall to ABI bytes
func (value PackedIntermediateCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes PackedIntermediateCall from ABI bytes in the provided buffer
func (t *PackedIntermediateCall) Decode(data []byte) (int, error) {
	if len(data) < 128 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 128
	// Decode static field U24: uint24
	t.U24, _, err = abi.DecodeUint24(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode static field U40: uint40
	t.U40, _, err = abi.DecodeUint40(data[32:])
	if err != nil {
		return 0, err
	}
	// Decode static field I24: int24
	t.I24, _, err = abi.DecodeInt24(data[64:])
	if err != nil {
		return 0, err
	}
	// Decode static field I40: int40
	t.I40, _, err = abi.DecodeInt40(data[96:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

// PackedEncodedSize returns the packed encoded size of PackedIntermediateCall
func (t PackedIntermediateCall) PackedEncodedSize() int {
	return 16
}

// PackedEncodeTo encodes PackedIntermediateCall to packed ABI bytes in the provided buffer
func (value PackedIntermediateCall) PackedEncodeTo(buf []byte) (int, error) {
	// Encode tuple fields sequentially (packed, no dynamic section)
	var (
		offset int
		n      int
		err    error
	)
	// Field U24: uint24
	n, err = abi.PackedEncodeUint24(value.U24, buf[offset:])
	if err != nil {
		return 0, err
	}
	offset += n

	// Field U40: uint40
	n, err = abi.PackedEncodeUint40(value.U40, buf[offset:])
	if err != nil {
		return 0, err
	}
	offset += n

	// Field I24: int24
	n, err = abi.PackedEncodeInt24(value.I24, buf[offset:])
	if err != nil {
		return 0, err
	}
	offset += n

	// Field I40: int40
	n, err = abi.PackedEncodeInt40(value.I40, buf[offset:])
	if err != nil {
		return 0, err
	}
	offset += n

	return offset, nil
}

// PackedEncode encodes PackedIntermediateCall to packed ABI bytes
func (value PackedIntermediateCall) PackedEncode() ([]byte, error) {
	buf := make([]byte, value.PackedEncodedSize())
	if _, err := value.PackedEncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// PackedDecode decodes PackedIntermediateCall from packed ABI bytes
func (t *PackedIntermediateCall) PackedDecode(data []byte) (int, error) {
	if len(data) < 16 {
		return 0, io.ErrUnexpectedEOF
	}
	var err error
	// Decode field U24: uint24
	t.U24, _, err = abi.PackedDecodeUint24(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode field U40: uint40
	t.U40, _, err = abi.PackedDecodeUint40(data[3:])
	if err != nil {
		return 0, err
	}
	// Decode field I24: int24
	t.I24, _, err = abi.PackedDecodeInt24(data[8:])
	if err != nil {
		return 0, err
	}
	// Decode field I40: int40
	t.I40, _, err = abi.PackedDecodeInt40(data[11:])
	if err != nil {
		return 0, err
	}
	return 16, nil
}

// GetMethodName returns the function name
func (t PackedIntermediateCall) GetMethodName() string {
	return "packedIntermediate"
}

// GetMethodID returns the function id
func (t PackedIntermediateCall) GetMethodID() uint32 {
	return PackedIntermediateID
}

// GetMethodSelector returns the function selector
func (t PackedIntermediateCall) GetMethodSelector() [4]byte {
	return PackedIntermediateSelector
}

// EncodeWithSelector encodes packedIntermediate arguments to ABI bytes including function selector
func (t PackedIntermediateCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], PackedIntermediateSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewPackedIntermediateCall constructs a new PackedIntermediateCall
func NewPackedIntermediateCall(
	u24 uint32,
	u40 uint64,
	i24 int32,
	i40 int64,
) *PackedIntermediateCall {
	return &PackedIntermediateCall{
		U24: u24,
		U40: u40,
		I24: i24,
		I40: i40,
	}
}

const PackedIntermediateReturnStaticSize = 32

var _ abi.Tuple = (*PackedIntermediateReturn)(nil)
var _ abi.PackedTuple = (*PackedIntermediateReturn)(nil)

// PackedIntermediateReturn represents an ABI tuple
type PackedIntermediateReturn struct {
	Field1 bool
}

// EncodedSize returns the total encoded size of PackedIntermediateReturn
func (t PackedIntermediateReturn) EncodedSize() int {
	dynamicSize := 0

	return PackedIntermediateReturnStaticSize + dynamicSize
}

// EncodeTo encodes PackedIntermediateReturn to ABI bytes in the provided buffer
func (value PackedIntermediateReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := PackedIntermediateReturnStaticSize // Start dynamic data after static section
	// Field Field1: bool
	if _, err := abi.EncodeBool(value.Field1, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes PackedIntermediateReturn to ABI bytes
func (value PackedIntermediateReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes PackedIntermediateReturn from ABI bytes in the provided buffer
func (t *PackedIntermediateReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field Field1: bool
	t.Field1, _, err = abi.DecodeBool(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

// PackedEncodedSize returns the packed encoded size of PackedIntermediateReturn
func (t PackedIntermediateReturn) PackedEncodedSize() int {
	return 1
}

// PackedEncodeTo encodes PackedIntermediateReturn to packed ABI bytes in the provided buffer
func (value PackedIntermediateReturn) PackedEncodeTo(buf []byte) (int, error) {
	// Encode tuple fields sequentially (packed, no dynamic section)
	var (
		offset int
		n      int
		err    error
	)
	// Field Field1: bool
	n, err = abi.PackedEncodeBool(value.Field1, buf[offset:])
	if err != nil {
		return 0, err
	}
	offset += n

	return offset, nil
}

// PackedEncode encodes PackedIntermediateReturn to packed ABI bytes
func (value PackedIntermediateReturn) PackedEncode() ([]byte, error) {
	buf := make([]byte, value.PackedEncodedSize())
	if _, err := value.PackedEncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// PackedDecode decodes PackedIntermediateReturn from packed ABI bytes
func (t *PackedIntermediateReturn) PackedDecode(data []byte) (int, error) {
	if len(data) < 1 {
		return 0, io.ErrUnexpectedEOF
	}
	var err error
	// Decode field Field1: bool
	t.Field1, _, err = abi.PackedDecodeBool(data[0:])
	if err != nil {
		return 0, err
	}
	return 1, nil
}

var _ abi.Method = (*PackedSmallIntsCall)(nil)

const PackedSmallIntsCallStaticSize = 256

var _ abi.Tuple = (*PackedSmallIntsCall)(nil)
var _ abi.PackedTuple = (*PackedSmallIntsCall)(nil)

// PackedSmallIntsCall represents an ABI tuple
type PackedSmallIntsCall struct {
	U8  uint8
	U16 uint16
	U32 uint32
	U64 uint64
	I8  int8
	I16 int16
	I32 int32
	I64 int64
}

// EncodedSize returns the total encoded size of PackedSmallIntsCall
func (t PackedSmallIntsCall) EncodedSize() int {
	dynamicSize := 0

	return PackedSmallIntsCallStaticSize + dynamicSize
}

// EncodeTo encodes PackedSmallIntsCall to ABI bytes in the provided buffer
func (value PackedSmallIntsCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := PackedSmallIntsCallStaticSize // Start dynamic data after static section
	// Field U8: uint8
	if _, err := abi.EncodeUint8(value.U8, buf[0:]); err != nil {
		return 0, err
	}

	// Field U16: uint16
	if _, err := abi.EncodeUint16(value.U16, buf[32:]); err != nil {
		return 0, err
	}

	// Field U32: uint32
	if _, err := abi.EncodeUint32(value.U32, buf[64:]); err != nil {
		return 0, err
	}

	// Field U64: uint64
	if _, err := abi.EncodeUint64(value.U64, buf[96:]); err != nil {
		return 0, err
	}

	// Field I8: int8
	if _, err := abi.EncodeInt8(value.I8, buf[128:]); err != nil {
		return 0, err
	}

	// Field I16: int16
	if _, err := abi.EncodeInt16(value.I16, buf[160:]); err != nil {
		return 0, err
	}

	// Field I32: int32
	if _, err := abi.EncodeInt32(value.I32, buf[192:]); err != nil {
		return 0, err
	}

	// Field I64: int64
	if _, err := abi.EncodeInt64(value.I64, buf[224:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes PackedSmallIntsCall to ABI bytes
func (value PackedSmallIntsCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes PackedSmallIntsCall from ABI bytes in the provided buffer
func (t *PackedSmallIntsCall) Decode(data []byte) (int, error) {
	if len(data) < 256 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 256
	// Decode static field U8: uint8
	t.U8, _, err = abi.DecodeUint8(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode static field U16: uint16
	t.U16, _, err = abi.DecodeUint16(data[32:])
	if err != nil {
		return 0, err
	}
	// Decode static field U32: uint32
	t.U32, _, err = abi.DecodeUint32(data[64:])
	if err != nil {
		return 0, err
	}
	// Decode static field U64: uint64
	t.U64, _, err = abi.DecodeUint64(data[96:])
	if err != nil {
		return 0, err
	}
	// Decode static field I8: int8
	t.I8, _, err = abi.DecodeInt8(data[128:])
	if err != nil {
		return 0, err
	}
	// Decode static field I16: int16
	t.I16, _, err = abi.DecodeInt16(data[160:])
	if err != nil {
		return 0, err
	}
	// Decode static field I32: int32
	t.I32, _, err = abi.DecodeInt32(data[192:])
	if err != nil {
		return 0, err
	}
	// Decode static field I64: int64
	t.I64, _, err = abi.DecodeInt64(data[224:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

// PackedEncodedSize returns the packed encoded size of PackedSmallIntsCall
func (t PackedSmallIntsCall) PackedEncodedSize() int {
	return 30
}

// PackedEncodeTo encodes PackedSmallIntsCall to packed ABI bytes in the provided buffer
func (value PackedSmallIntsCall) PackedEncodeTo(buf []byte) (int, error) {
	// Encode tuple fields sequentially (packed, no dynamic section)
	var (
		offset int
		n      int
		err    error
	)
	// Field U8: uint8
	n, err = abi.PackedEncodeUint8(value.U8, buf[offset:])
	if err != nil {
		return 0, err
	}
	offset += n

	// Field U16: uint16
	n, err = abi.PackedEncodeUint16(value.U16, buf[offset:])
	if err != nil {
		return 0, err
	}
	offset += n

	// Field U32: uint32
	n, err = abi.PackedEncodeUint32(value.U32, buf[offset:])
	if err != nil {
		return 0, err
	}
	offset += n

	// Field U64: uint64
	n, err = abi.PackedEncodeUint64(value.U64, buf[offset:])
	if err != nil {
		return 0, err
	}
	offset += n

	// Field I8: int8
	n, err = abi.PackedEncodeInt8(value.I8, buf[offset:])
	if err != nil {
		return 0, err
	}
	offset += n

	// Field I16: int16
	n, err = abi.PackedEncodeInt16(value.I16, buf[offset:])
	if err != nil {
		return 0, err
	}
	offset += n

	// Field I32: int32
	n, err = abi.PackedEncodeInt32(value.I32, buf[offset:])
	if err != nil {
		return 0, err
	}
	offset += n

	// Field I64: int64
	n, err = abi.PackedEncodeInt64(value.I64, buf[offset:])
	if err != nil {
		return 0, err
	}
	offset += n

	return offset, nil
}

// PackedEncode encodes PackedSmallIntsCall to packed ABI bytes
func (value PackedSmallIntsCall) PackedEncode() ([]byte, error) {
	buf := make([]byte, value.PackedEncodedSize())
	if _, err := value.PackedEncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// PackedDecode decodes PackedSmallIntsCall from packed ABI bytes
func (t *PackedSmallIntsCall) PackedDecode(data []byte) (int, error) {
	if len(data) < 30 {
		return 0, io.ErrUnexpectedEOF
	}
	var err error
	// Decode field U8: uint8
	t.U8, _, err = abi.PackedDecodeUint8(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode field U16: uint16
	t.U16, _, err = abi.PackedDecodeUint16(data[1:])
	if err != nil {
		return 0, err
	}
	// Decode field U32: uint32
	t.U32, _, err = abi.PackedDecodeUint32(data[3:])
	if err != nil {
		return 0, err
	}
	// Decode field U64: uint64
	t.U64, _, err = abi.PackedDecodeUint64(data[7:])
	if err != nil {
		return 0, err
	}
	// Decode field I8: int8
	t.I8, _, err = abi.PackedDecodeInt8(data[15:])
	if err != nil {
		return 0, err
	}
	// Decode field I16: int16
	t.I16, _, err = abi.PackedDecodeInt16(data[16:])
	if err != nil {
		return 0, err
	}
	// Decode field I32: int32
	t.I32, _, err = abi.PackedDecodeInt32(data[18:])
	if err != nil {
		return 0, err
	}
	// Decode field I64: int64
	t.I64, _, err = abi.PackedDecodeInt64(data[22:])
	if err != nil {
		return 0, err
	}
	return 30, nil
}

// GetMethodName returns the function name
func (t PackedSmallIntsCall) GetMethodName() string {
	return "packedSmallInts"
}

// GetMethodID returns the function id
func (t PackedSmallIntsCall) GetMethodID() uint32 {
	return PackedSmallIntsID
}

// GetMethodSelector returns the function selector
func (t PackedSmallIntsCall) GetMethodSelector() [4]byte {
	return PackedSmallIntsSelector
}

// EncodeWithSelector encodes packedSmallInts arguments to ABI bytes including function selector
func (t PackedSmallIntsCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], PackedSmallIntsSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewPackedSmallIntsCall constructs a new PackedSmallIntsCall
func NewPackedSmallIntsCall(
	u8 uint8,
	u16 uint16,
	u32 uint32,
	u64 uint64,
	i8 int8,
	i16 int16,
	i32 int32,
	i64 int64,
) *PackedSmallIntsCall {
	return &PackedSmallIntsCall{
		U8:  u8,
		U16: u16,
		U32: u32,
		U64: u64,
		I8:  i8,
		I16: i16,
		I32: i32,
		I64: i64,
	}
}

const PackedSmallIntsReturnStaticSize = 32

var _ abi.Tuple = (*PackedSmallIntsReturn)(nil)
var _ abi.PackedTuple = (*PackedSmallIntsReturn)(nil)

// PackedSmallIntsReturn represents an ABI tuple
type PackedSmallIntsReturn struct {
	Field1 bool
}

// EncodedSize returns the total encoded size of PackedSmallIntsReturn
func (t PackedSmallIntsReturn) EncodedSize() int {
	dynamicSize := 0

	return PackedSmallIntsReturnStaticSize + dynamicSize
}

// EncodeTo encodes PackedSmallIntsReturn to ABI bytes in the provided buffer
func (value PackedSmallIntsReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := PackedSmallIntsReturnStaticSize // Start dynamic data after static section
	// Field Field1: bool
	if _, err := abi.EncodeBool(value.Field1, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes PackedSmallIntsReturn to ABI bytes
func (value PackedSmallIntsReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes PackedSmallIntsReturn from ABI bytes in the provided buffer
func (t *PackedSmallIntsReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field Field1: bool
	t.Field1, _, err = abi.DecodeBool(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

// PackedEncodedSize returns the packed encoded size of PackedSmallIntsReturn
func (t PackedSmallIntsReturn) PackedEncodedSize() int {
	return 1
}

// PackedEncodeTo encodes PackedSmallIntsReturn to packed ABI bytes in the provided buffer
func (value PackedSmallIntsReturn) PackedEncodeTo(buf []byte) (int, error) {
	// Encode tuple fields sequentially (packed, no dynamic section)
	var (
		offset int
		n      int
		err    error
	)
	// Field Field1: bool
	n, err = abi.PackedEncodeBool(value.Field1, buf[offset:])
	if err != nil {
		return 0, err
	}
	offset += n

	return offset, nil
}

// PackedEncode encodes PackedSmallIntsReturn to packed ABI bytes
func (value PackedSmallIntsReturn) PackedEncode() ([]byte, error) {
	buf := make([]byte, value.PackedEncodedSize())
	if _, err := value.PackedEncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// PackedDecode decodes PackedSmallIntsReturn from packed ABI bytes
func (t *PackedSmallIntsReturn) PackedDecode(data []byte) (int, error) {
	if len(data) < 1 {
		return 0, io.ErrUnexpectedEOF
	}
	var err error
	// Decode field Field1: bool
	t.Field1, _, err = abi.PackedDecodeBool(data[0:])
	if err != nil {
		return 0, err
	}
	return 1, nil
}

var _ abi.Method = (*PackedStructCall)(nil)

const PackedStructCallStaticSize = 96

var _ abi.Tuple = (*PackedStructCall)(nil)
var _ abi.PackedTuple = (*PackedStructCall)(nil)

// PackedStructCall represents an ABI tuple
type PackedStructCall struct {
	S PackedStruct
}

// EncodedSize returns the total encoded size of PackedStructCall
func (t PackedStructCall) EncodedSize() int {
	dynamicSize := 0

	return PackedStructCallStaticSize + dynamicSize
}

// EncodeTo encodes PackedStructCall to ABI bytes in the provided buffer
func (value PackedStructCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := PackedStructCallStaticSize // Start dynamic data after static section
	// Field S: (address,uint256,bytes32)
	if _, err := value.S.EncodeTo(buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes PackedStructCall to ABI bytes
func (value PackedStructCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes PackedStructCall from ABI bytes in the provided buffer
func (t *PackedStructCall) Decode(data []byte) (int, error) {
	if len(data) < 96 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 96
	// Decode static field S: (address,uint256,bytes32)
	_, err = t.S.Decode(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

// PackedEncodedSize returns the packed encoded size of PackedStructCall
func (t PackedStructCall) PackedEncodedSize() int {
	return 84
}

// PackedEncodeTo encodes PackedStructCall to packed ABI bytes in the provided buffer
func (value PackedStructCall) PackedEncodeTo(buf []byte) (int, error) {
	// Encode tuple fields sequentially (packed, no dynamic section)
	var (
		offset int
		n      int
		err    error
	)
	// Field S: (address,uint256,bytes32)
	n, err = value.S.PackedEncodeTo(buf[offset:])
	if err != nil {
		return 0, err
	}
	offset += n

	return offset, nil
}

// PackedEncode encodes PackedStructCall to packed ABI bytes
func (value PackedStructCall) PackedEncode() ([]byte, error) {
	buf := make([]byte, value.PackedEncodedSize())
	if _, err := value.PackedEncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// PackedDecode decodes PackedStructCall from packed ABI bytes
func (t *PackedStructCall) PackedDecode(data []byte) (int, error) {
	if len(data) < 84 {
		return 0, io.ErrUnexpectedEOF
	}
	var err error
	// Decode field S: (address,uint256,bytes32)
	_, err = t.S.PackedDecode(data[0:])
	if err != nil {
		return 0, err
	}
	return 84, nil
}

// GetMethodName returns the function name
func (t PackedStructCall) GetMethodName() string {
	return "packedStruct"
}

// GetMethodID returns the function id
func (t PackedStructCall) GetMethodID() uint32 {
	return PackedStructID
}

// GetMethodSelector returns the function selector
func (t PackedStructCall) GetMethodSelector() [4]byte {
	return PackedStructSelector
}

// EncodeWithSelector encodes packedStruct arguments to ABI bytes including function selector
func (t PackedStructCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], PackedStructSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewPackedStructCall constructs a new PackedStructCall
func NewPackedStructCall(
	s PackedStruct,
) *PackedStructCall {
	return &PackedStructCall{
		S: s,
	}
}

const PackedStructReturnStaticSize = 32

var _ abi.Tuple = (*PackedStructReturn)(nil)
var _ abi.PackedTuple = (*PackedStructReturn)(nil)

// PackedStructReturn represents an ABI tuple
type PackedStructReturn struct {
	Field1 bool
}

// EncodedSize returns the total encoded size of PackedStructReturn
func (t PackedStructReturn) EncodedSize() int {
	dynamicSize := 0

	return PackedStructReturnStaticSize + dynamicSize
}

// EncodeTo encodes PackedStructReturn to ABI bytes in the provided buffer
func (value PackedStructReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := PackedStructReturnStaticSize // Start dynamic data after static section
	// Field Field1: bool
	if _, err := abi.EncodeBool(value.Field1, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes PackedStructReturn to ABI bytes
func (value PackedStructReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes PackedStructReturn from ABI bytes in the provided buffer
func (t *PackedStructReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field Field1: bool
	t.Field1, _, err = abi.DecodeBool(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

// PackedEncodedSize returns the packed encoded size of PackedStructReturn
func (t PackedStructReturn) PackedEncodedSize() int {
	return 1
}

// PackedEncodeTo encodes PackedStructReturn to packed ABI bytes in the provided buffer
func (value PackedStructReturn) PackedEncodeTo(buf []byte) (int, error) {
	// Encode tuple fields sequentially (packed, no dynamic section)
	var (
		offset int
		n      int
		err    error
	)
	// Field Field1: bool
	n, err = abi.PackedEncodeBool(value.Field1, buf[offset:])
	if err != nil {
		return 0, err
	}
	offset += n

	return offset, nil
}

// PackedEncode encodes PackedStructReturn to packed ABI bytes
func (value PackedStructReturn) PackedEncode() ([]byte, error) {
	buf := make([]byte, value.PackedEncodedSize())
	if _, err := value.PackedEncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// PackedDecode decodes PackedStructReturn from packed ABI bytes
func (t *PackedStructReturn) PackedDecode(data []byte) (int, error) {
	if len(data) < 1 {
		return 0, io.ErrUnexpectedEOF
	}
	var err error
	// Decode field Field1: bool
	t.Field1, _, err = abi.PackedDecodeBool(data[0:])
	if err != nil {
		return 0, err
	}
	return 1, nil
}

var _ abi.Method = (*PackedTransferCall)(nil)

const PackedTransferCallStaticSize = 64

var _ abi.Tuple = (*PackedTransferCall)(nil)
var _ abi.PackedTuple = (*PackedTransferCall)(nil)

// PackedTransferCall represents an ABI tuple
type PackedTransferCall struct {
	To     common.Address
	Amount *big.Int
}

// EncodedSize returns the total encoded size of PackedTransferCall
func (t PackedTransferCall) EncodedSize() int {
	dynamicSize := 0

	return PackedTransferCallStaticSize + dynamicSize
}

// EncodeTo encodes PackedTransferCall to ABI bytes in the provided buffer
func (value PackedTransferCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := PackedTransferCallStaticSize // Start dynamic data after static section
	// Field To: address
	if _, err := abi.EncodeAddress(value.To, buf[0:]); err != nil {
		return 0, err
	}

	// Field Amount: uint256
	if _, err := abi.EncodeUint256(value.Amount, buf[32:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes PackedTransferCall to ABI bytes
func (value PackedTransferCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes PackedTransferCall from ABI bytes in the provided buffer
func (t *PackedTransferCall) Decode(data []byte) (int, error) {
	if len(data) < 64 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 64
	// Decode static field To: address
	t.To, _, err = abi.DecodeAddress(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode static field Amount: uint256
	t.Amount, _, err = abi.DecodeUint256(data[32:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

// PackedEncodedSize returns the packed encoded size of PackedTransferCall
func (t PackedTransferCall) PackedEncodedSize() int {
	return 52
}

// PackedEncodeTo encodes PackedTransferCall to packed ABI bytes in the provided buffer
func (value PackedTransferCall) PackedEncodeTo(buf []byte) (int, error) {
	// Encode tuple fields sequentially (packed, no dynamic section)
	var (
		offset int
		n      int
		err    error
	)
	// Field To: address
	n, err = abi.PackedEncodeAddress(value.To, buf[offset:])
	if err != nil {
		return 0, err
	}
	offset += n

	// Field Amount: uint256
	n, err = abi.PackedEncodeUint256(value.Amount, buf[offset:])
	if err != nil {
		return 0, err
	}
	offset += n

	return offset, nil
}

// PackedEncode encodes PackedTransferCall to packed ABI bytes
func (value PackedTransferCall) PackedEncode() ([]byte, error) {
	buf := make([]byte, value.PackedEncodedSize())
	if _, err := value.PackedEncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// PackedDecode decodes PackedTransferCall from packed ABI bytes
func (t *PackedTransferCall) PackedDecode(data []byte) (int, error) {
	if len(data) < 52 {
		return 0, io.ErrUnexpectedEOF
	}
	var err error
	// Decode field To: address
	t.To, _, err = abi.PackedDecodeAddress(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode field Amount: uint256
	t.Amount, _, err = abi.PackedDecodeUint256(data[20:])
	if err != nil {
		return 0, err
	}
	return 52, nil
}

// GetMethodName returns the function name
func (t PackedTransferCall) GetMethodName() string {
	return "packedTransfer"
}

// GetMethodID returns the function id
func (t PackedTransferCall) GetMethodID() uint32 {
	return PackedTransferID
}

// GetMethodSelector returns the function selector
func (t PackedTransferCall) GetMethodSelector() [4]byte {
	return PackedTransferSelector
}

// EncodeWithSelector encodes packedTransfer arguments to ABI bytes including function selector
func (t PackedTransferCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], PackedTransferSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewPackedTransferCall constructs a new PackedTransferCall
func NewPackedTransferCall(
	to common.Address,
	amount *big.Int,
) *PackedTransferCall {
	return &PackedTransferCall{
		To:     to,
		Amount: amount,
	}
}

const PackedTransferReturnStaticSize = 32

var _ abi.Tuple = (*PackedTransferReturn)(nil)
var _ abi.PackedTuple = (*PackedTransferReturn)(nil)

// PackedTransferReturn represents an ABI tuple
type PackedTransferReturn struct {
	Field1 bool
}

// EncodedSize returns the total encoded size of PackedTransferReturn
func (t PackedTransferReturn) EncodedSize() int {
	dynamicSize := 0

	return PackedTransferReturnStaticSize + dynamicSize
}

// EncodeTo encodes PackedTransferReturn to ABI bytes in the provided buffer
func (value PackedTransferReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := PackedTransferReturnStaticSize // Start dynamic data after static section
	// Field Field1: bool
	if _, err := abi.EncodeBool(value.Field1, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes PackedTransferReturn to ABI bytes
func (value PackedTransferReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes PackedTransferReturn from ABI bytes in the provided buffer
func (t *PackedTransferReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field Field1: bool
	t.Field1, _, err = abi.DecodeBool(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

// PackedEncodedSize returns the packed encoded size of PackedTransferReturn
func (t PackedTransferReturn) PackedEncodedSize() int {
	return 1
}

// PackedEncodeTo encodes PackedTransferReturn to packed ABI bytes in the provided buffer
func (value PackedTransferReturn) PackedEncodeTo(buf []byte) (int, error) {
	// Encode tuple fields sequentially (packed, no dynamic section)
	var (
		offset int
		n      int
		err    error
	)
	// Field Field1: bool
	n, err = abi.PackedEncodeBool(value.Field1, buf[offset:])
	if err != nil {
		return 0, err
	}
	offset += n

	return offset, nil
}

// PackedEncode encodes PackedTransferReturn to packed ABI bytes
func (value PackedTransferReturn) PackedEncode() ([]byte, error) {
	buf := make([]byte, value.PackedEncodedSize())
	if _, err := value.PackedEncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// PackedDecode decodes PackedTransferReturn from packed ABI bytes
func (t *PackedTransferReturn) PackedDecode(data []byte) (int, error) {
	if len(data) < 1 {
		return 0, io.ErrUnexpectedEOF
	}
	var err error
	// Decode field Field1: bool
	t.Field1, _, err = abi.PackedDecodeBool(data[0:])
	if err != nil {
		return 0, err
	}
	return 1, nil
}
